### ISSUE TITLE
error with low SD

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#10]
Does not work if you run a 3w*3w with SD = 0.1659, and means:
0.9861, 0.9861, 0.9931, 0.4861, 0.2986, 0.4653, 0.0417, 0.0278, 0.0278
Will give a disconnect from server after a while. Maybe due to low SD

**Comment by arcaldwell49** [comment]
Good catch. Within R the error messages from the "design" and "power" functions 
![error](https://user-images.githubusercontent.com/24322628/45239615-7660b080-b2ab-11e8-963b-639862086c8a.png)

Will continue to look into this over the weekend.

**Comment by arcaldwell49** [comment]
Okay, temporary solution is an error message stating "Sorry, the correlation must be greater than the standard deviation" when r > sd

**Comment by arcaldwell49** [comment]
New correlation matrix solution has solved this problem.
