### ISSUE TITLE
large N require too big vector

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#13]
When trying with n = 10000, I get the error:
 Error: cannot allocate vector of size 6.7 Gb 

The code: 
aov_car(frml1, #here we use frml1 to enter fromula 1 as designed above on the basis of the design 
                                          data=df,
                                          anova_table = list(es = "pes", p_adjust_method = p_adjust))})

also takes VERY long with large N. 

This is greatly sped up by ading: return = "nice" - however, then the function:
pairs(emmeans(aov_result, frml2), adjust = p_adjust)
no longer works. We need to find an alternative to the contrasts - then we can greatly speed up the efficiency. 

We might be able to use some other functions for the contrasts?

**Comment by arcaldwell49** [comment]
I have tried the include_aov function (Henrik's suggestion) but only marginally improves the speed. Something we need to consider moving forward.

**Comment by Lakens** [comment]
Related to #16

**Comment by Lakens** [comment]
This is fixed using the newest version of AFEX (even though simulations will always take long with huge N, at least no error message).
