### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#14]
Is it possible with your APP to calculate power for a design with:
2b*2b*2w
 
This means that I have:
one between factor with two levels
one between factor with two levels
one within factor with two levels
 
When I put all information in the APP it says "An error has occured. Check your logs or contact the app author for clarification."
I wonder if the APP is made for a 2x2x2 ANOVA.

**Comment by arcaldwell49** [comment]
The problem is with the sigmatrix. Trying to trace back where the exact issue is.

**Comment by arcaldwell49** [comment]
Recent update should resolve problem.
