### ISSUE TITLE
Change oav_car in afex package to return = nice to speed up simulation for large N

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#16]
This requires we pull the results from the output object in a different way than we do now.

**Comment by Lakens** [comment]
Related to #13

**Comment by arcaldwell49** [comment]
My only concern with this approach is that p < .0001 is output as '<.0001' rather than the exact p value.

**Comment by arcaldwell49** [comment]
Using nice, in comparison to include_aov = FALSE, is not resulting in much faster speed of aov_result
