### ISSUE TITLE
do we need development version of afex (not on shiny) or not? 

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#17]

**Comment by arcaldwell49** [comment]
We do not need it, but it will run faster with the developmental afex because of the `include_aov` option.

**Comment by arcaldwell49** [comment]
We will need the development version (at least for now) because the include_aov option is needed in order to speed up the ANOVA_power function. I would now strongly advocate for using this moving forward because it is immensely faster (15-20x in some cases)

**Comment by Lakens** [comment]
OK - it is now installed everywhere. We should include this information in how to use the package.

**Comment by Lakens** [comment]
I think afex is now updated on CRAN.
