### ISSUE TITLE
order bars in plot in the same order as entered. 

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#19]
`string <- "3w"
n <- 50
# We are thinking of running 50 peope in each condition
mu <- c(24, 25.2, 25.4)
# Enter means in the order that matches the labels below.
# In this case, control, cat, dog. 
sd <- 6.4
r <- 0 
# (note that since we simulate a between design, the correlation between variables 
# will be 0, regardless of what you enter here, but the value must be set).
p_adjust = "none"
# "none" means we do not correct for multiple comparisons
labelnames <- c("condition", "control", "cat", "dog") #
# the label names should be in the order of the means specified above.

design_result <- ANOVA_design(string = string,
                   n = n, 
                   mu = mu, 
                   sd = sd, 
                   r = r, 
                   p_adjust = p_adjust,
                   labelnames = labelnames)
`
Returns a plot with 3 plotted means and CI. but they are in alphabetical ordel (cat, control, dog) whereas it makes more sense to present them in the order entered. We did notice before because we use factor1, factor2.

**Comment by arcaldwell49** [comment]
Ordered factors is now accommodated in the meansplot for ANOVA_design

**Comment by Lakens** [comment]
A new error is introduced and ANOVA design stops at: 
colourCount = length(unique(labelnameslist[[2]]))
when running a within subject ANOVA. 
Error is: Error in labelnameslist[[2]] : subscript out of bounds

**Comment by arcaldwell49** [comment]
That is my fault. I had the logical operator `&` rather than `&&`. The latter works because if `factors ==1` then `length(labelnameslist[[2]]) >= 9` is not evaluated.  New version of ANOVA_design works with single, 2, and 3-factor designs as well as those with factor lengths > 9.
