### ISSUE TITLE
there is no error if the number of labelnames does not match the number of levels. 

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#20]
Build in a check to make sure they match when users input the values, or throw a warning.

**Comment by arcaldwell49** [comment]
Alright, I have a fix written. I'll push it GitHub soon

`  if (length(labelnames) != length(as.numeric(strsplit(string, "\\D+")[[1]])) + sum(as.numeric(strsplit(string, "\\D+")[[1]]))) {
    stop("Design (string) does not match the length of the labelnames")
  }`
