### ISSUE TITLE
Correlation matrix incorrect for 2x2x2 design

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#25]
string <- "2b*2b*2w"
n <- 50
mu <- c(1, 1, 3, 1, 3, 3, 1, 3) #All means are equal - so there is no real difference.
sd <- 5
r <- 0.5 
p_adjust = "none"
labelnames <- c("Size", "big", "small", "Color", "green", "red", "Cognitive_Load", "present", "absent") #

design_result <- ANOVA_design(string = string,
                   n = n, 
                   mu = mu, 
                   sd = sd, 
                   r = r, 
                   p_adjust = p_adjust,
                   labelnames = labelnames)

design_result$cor_mat

Gives: 
   X1  X2  X3  X4  X5  X6  X7  X8
1 1.0 0.5 0.0 0.0 0.0 0.0 0.0 0.0
2 0.5 1.0 0.0 0.0 0.0 0.0 0.0 0.0
3 0.0 0.0 1.0 0.5 0.0 0.0 0.0 0.0
4 0.0 0.0 0.5 1.0 0.0 0.0 0.0 0.0
5 0.0 0.0 0.0 0.0 1.0 0.5 0.0 0.0
6 0.0 0.0 0.0 0.0 0.5 1.0 0.0 0.0
7 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.5
8 0.0 0.0 0.0 0.0 0.0 0.0 0.5 1.0

**Comment by arcaldwell49** [comment]
For a 2 x 2 x 2 with the last factor being 2w wouldn't this correlation matrix be correct? 

The column labels below would make sense that the matching a and b with different c would be correlated. right?

A_1_B_1_C_1 -- A_1_B_1_C_2 -- A_1_B_2_C_1 -- A_1_B_2_C_2 -- A_2_B_1_C_1 -- A_2_B_1_C_2 -- A_2_B_2_C_1 -- A_2_B_2_C_2

**Comment by Lakens** [comment]
My bad - was working till late and this was a last message when trying to check 3-way designs. You are right, the matrix is fine. My bad.
