### ISSUE TITLE
effect sizes for contrasts

### ISSUE THREAD

**Issue by Lakens** [Lakens/ANOVA_power_simulation#4]
Now Calculating Cohen's dz for within designs - but not correct for between designs. Make the calculation dependent upon the design (within between).

**Comment by Lakens** [comment]
pairs in lsmeans provides t-values and df - so should be able to just use df+1 or df+2 

as.numeric(strsplit(string, "\\D+")[[1]])*design 
gives the within factors.

**Comment by Lakens** [comment]
fixed using ifelse statement = now effect size is d for between tests, dz for within test.

**Comment by Lakens** [comment]
This still seems to be wrong. effect sizes for paired contrasts are too large (see Validation of Power in Repeated Measures ANOVA replicating Brysbaert). Check the calculated ES. Power seems to be good - might be a bit too high (but within a %) based on simulations so far.

**Comment by arcaldwell49** [comment]
Hmm, took a quick this morning and it appears in this scenario it is identifying the design as between rather than within.  The snippet below is the problem.
`# store p-values and effect sizes for calculations and plots.
      sim_data[i,] <- c(aov_result$anova_table[[6]], #p-value for ANOVA
                        aov_result$anova_table[[5]], #partial eta squared
                        as.data.frame(summary(pc))$p.value, #p-values for paired comparisons
                        ifelse(as.data.frame(summary(pc))$df == n-1, #if df = n-1 (means within factor)
                               (as.data.frame(summary(pc))$t.ratio/sqrt(n))*(1-(3/(4*(n-1)-1))), #Cohen's dz for within # g correction *(1-(3/(4*(n-1)-1)))
                               (2 * as.data.frame(summary(pc))$t.ratio)/sqrt(2*n)*(1-(3/(4*(2*n-2)-1))))) #Cohen's d for between # g correction *(1-(3/(4*(2*n-2)-1)))
   `

**Comment by Lakens** [comment]
Yep - will fix it today. And create a validation document for this specific code.

**Comment by Lakens** [comment]
Fixed
